name: ElementalStones
version: ${project.version}
main: com.lennertsoffers.elementalstones.ElementalStones
api-version: 1.16
authors: [ lennertsoffers ]
description: A Minecraft Spigot plugin to add elemental stones to your server
libraries:
  - org.apache.commons:commons-text:1.10.0

commands:
  checkConsumables:
    description: Open an inventory of all the consumables in the plugin
    usage: /checkConsumables
  checkItems:
    description: Open an inventory of all the base items in the plugin
    usage: /checkItems
  checkShards:
    description: Open an inventory with all the shards in the plugin
    usage: /checkShards
  checkSpells:
    description: Open an inventory with all the spells in the plugin
    usage: /checkSpells
  getCustomModelData:
    description: Sends message to the player with the custom model data of the itemstack he's holding
    usage: /getCustomModelData
  lowerHunger:
    description: Sets the hunger level to 1
    usage: /lowerHunger
  r:
    description: Reloads the server and kicks all online players
    usage: /r
  saveDefaultConfig:
    description: Saves the default config file
    usage: /saveDefaultConfig
  spawnBoss:
    description: Summons a random boss
    usage: /spawnBoss
  stoneInventory:
    description: Opens inventory where you can pick a stone from
    usage: /stoneInventory <water-fire-air-earth>
  testTargets:
    description: Spawns 100 cows to test the stones on
    usage: testTargets
